{% set name = "Werkzeug" %}
{% set version = "0.11.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e72c46bc14405cba7a26bd2ce28df734471bc9016bc8b4cb69466c2c14c2f7e5

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - werkzeug
    - werkzeug.debug

about:
  home: https://palletsprojects.com/p/werkzeug/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: The comprehensive WSGI web application library.
  description: |
    Werkzeug is a WSGI utility library for Python. It's widely used and BSD licensed.
  doc_url: https://werkzeug.palletsprojects.com/
  dev_url: https://github.com/pallets/werkzeug

extra:
  recipe-maintainers:
    - goanpeca
    - mcs07
