travis:
  secure:
    BINSTAR_TOKEN: ZGttgaqfkXmWOhgbFRduKc/7pMidix+KGgJF/5IHzLSZgDM6P1Gslkd5SsCQ0LHLHJWZxUmJ3nzMIXe+wwu/jdbKdF7k1u7XrasW4hmmrMbnbhlwPCjHCmFFUIaaN7S5MqevNHXL8zfA1WqUZLlFiyxyQMJ7Bf+5MYbyr+3QsupBSTG1ORM1PJXieBemX8mJI0Tt9Hffxu+l3Jt9/Qvs+aJo7L/5DqASfP2hSAR81+OoV1Lt2hCWalSUbIfFfOEnB1b0C//j6HefQsl/ZgQHySoVI0WKCDzUgD+MlbPlrcuj1XrR2r3sVqdOi8XW1GS82FEXyx72FmD8ZUOMeOzdZjxhuLTYVPfaT2nTmBp6kpvqeOPQAj4xfA+2RpTmNhMNMkmn/2DDJNWOl5LNoXuh8CDZg8r0RddDsLN0sKJF1HCB3FOv7eGeGhhzbucbmyS4UwYt+VRfv5oZWUzwVIPv4C4jaxoZMODgbpNNFJMcWeBNyJjN6IgNNDrndx8ptk1CDlnSWBke3iK82bULQhGtUGg8QG6ZInW8XUXHb3qk7nn10hKbPCDV0CgK+YYRInKcrToIwpCmWohu5ev04aFdSCSIRg9dN94DE1qSEBP1QlpoB/kT9hnYfXfdZm8o3VopStH50fT5RVbM4OkAuC6jJyZrx7U6vcLfT8TIdwaAVCw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
